### ISSUE TITLE
9/12 Project Review

### ISSUE THREAD

**Issue by BCrawfordScott** [shiykim/pulsifys#2]
Auth: 
- [x] Fix homepage styling for a full screen with no console open (styling looks great, but needs to be formatted for a full screen.) 
- [x] Add styling to session forms
- [x] Fix 500 level server error on sign up and login.  (Great though that you're collecting the errors)

Ping me when you've fixed that 500 level error and sign up/log in are working.  Keep up the good work!

**Comment by shiykim** [comment]
Hi Brian! I'm not quite sure what you mean about full screen styling, but I think it may be fixed now? Let me know the styling of the homepage still looks off to you!
